In [2]:
import pandas as pd

df_cctv_seoul = pd.read_csv("D:\Study\TeamProject_2\CCTV_API_Test\CCTV_Seoul.csv")
df_stream_urls_seoul = pd.read_csv("D:\Study\TeamProject_2\CCTV_API_Test\stream_urls.csv")
df = pd.concat([df_cctv_seoul, df_stream_urls_seoul], axis=1)
df.head(5)

,index,CCTVID,CCTVNAME,CENTERNAME,XCOORD,YCOORD,StreamURL
0,6403,L010001,"2,3호터널",서울교통정보센터,126.989050,37.543920,http://210.179.218.53:1935/live/291.stream/pla...
1,6404,L010002,3기동단 4거리,서울교통정보센터,127.118498,37.480437,http://210.179.218.53:1935/live/322.stream/pla...
2,6405,L010003,63빌딩,서울교통정보센터,126.940140,37.519610,http://210.179.218.51:1935/live/83.stream/play...
3,6406,L010004,AT센터,서울교통정보센터,127.038870,37.469765,http://210.179.218.54:1935/live/333.stream/pla...
4,6407,L010005,가락시장,서울교통정보센터,127.113890,37.497330,http://210.179.218.52:1935/live/231.stream/pla...

In [3]:
df = df[["CCTVID", "CCTVNAME", "StreamURL"]]
df.head(5)

    CCTVID  CCTVNAME                                          StreamURL
0  L010001    2,3호터널  http://210.179.218.53:1935/live/291.stream/pla...
1  L010002  3기동단 4거리  http://210.179.218.53:1935/live/322.stream/pla...
2  L010003      63빌딩  http://210.179.218.51:1935/live/83.stream/play...
3  L010004      AT센터  http://210.179.218.54:1935/live/333.stream/pla...
4  L010005      가락시장  http://210.179.218.52:1935/live/231.stream/pla...

In [4]:
df.to_csv("CCTVID_URL")